apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exam-app
  template:
    metadata:
      labels:
        app: exam-app
    spec:
      containers:
      - name: laravel-web
        image: sereymony01/exam-laravel:latest
        ports:
        - containerPort: 8080
        - containerPort: 22
        env:
        - name: DB_CONNECTION
          value: mysql
        - name: DB_HOST
          value: 127.0.0.1
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          value: sereymony-db
        - name: DB_USERNAME
          value: root
        - name: DB_PASSWORD
          value: Hello@123

      - name: mysql
        image: mysql:8
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: Hello@123
        - name: MYSQL_DATABASE
          value: sereymony-db
